#!/bin/sh

exec java -classpath .:/usr/share/java/saxon.jar:/usr/share/java/xml-resolver.jar com.icl.saxon.StyleSheet -r org.apache.xml.resolver.tools.CatalogResolver -x org.apache.xml.resolver.tools.ResolvingXMLReader -y org.apache.xml.resolver.tools.ResolvingXMLReader "$@"
